### ISSUE TITLE
Add CellBuilder.py to pyNeuroML

### ISSUE THREAD

**Issue by pgleeson** [NeuroML/pyNeuroML#170] opened 2022-06-16 10:53 UTC
A useful utility script for creating NML cells is here: https://github.com/NeuroML/Documentation/blob/master/source/Userdocs/NML2_examples/CellBuilder.py and has used in this example: https://docs.neuroml.org/Userdocs/MultiCompartmentOLMexample.html

This should ideally be easily accessible to anyone using pyNeuroML (probably better than adding to libNeuroML, as some other helper/utility functions may be required).

Have started adding this here and updating it, but a better location could be found: https://github.com/NeuroML/pyNeuroML/tree/experimental/pyneuroml/morphologies

**Comment by sanjayankur31** [comment] 2022-07-26 10:11
Duplicate of #105. I think this is now ready in #107

**Closed by sanjayankur31** 2022-07-26 10:11 UTC
