### ISSUE TITLE
LEMS files unexpectedly have to be pritty-printed

### ISSUE THREAD

**Issue by jonrkarr** [NeuroML/pyNeuroML#100] opened 2021-06-04 05:35 UTC
**Describe the bug**
The execution of LEMS files fails when files aren't pretty-printed. This is odd because XML files don't generally have to be formatted in a particular way.

**To Reproduce**
```python
from pyneuroml.pynml import run_lems_with_jneuroml
import re

filename = 'tests/fixtures/LEMS_NML2_Ex5_DetCell.xml'
with open(filename, 'r') as file:
    contents=file.read()

# create a non-pretty-printed copy of the example LEMS file
filename_with_error = 'tests/fixtures/LEMS_NML2_Ex5_DetCell-with-error.xml'
contents=re.sub(' +', '', contents.replace('\n', ''))
with open(filename_with_error, 'w') as file:
    file.write(contents)

# succeeds
run_lems_with_jneuroml(filename, nogui=True, plot=False)

# fails
run_lems_with_jneuroml(filename_with_error, nogui=True, plot=False)
```

**Expected behavior**
Be able to read files whether they are pretty-printed or not

**Observed behavior**
```sh
pyNeuroML >>> *** Problem running command: 
pyNeuroML >>>        Command 'java -Xmx400M  -Djava.awt.headless=true -jar  "/home/jonrkarr/.local/lib/python3.9/site-packages/pyneuroml/lib/jNeuroML-0.10.3-jar-with-dependencies.jar"  "tests/fixtures/LEMS_NML2_Ex5_DetCell-with-error.xml"  -nogui -I ''' returned non-zero exit status 1.
pyNeuroML >>>  jNeuroML >>   jNeuroML v0.10.3
pyNeuroML >>>  jNeuroML >>  Loading: /home/jonrkarr/Documents/Biosimulators_pyNeuroML/tests/fixtures/LEMS_NML2_Ex5_DetCell-with-error.xml with jLEMS, NO GUI mode...
pyNeuroML >>>  jNeuroML >>  org.lemsml.jlems.core.sim.ContentError: No such type Targetcomponent="sim1"reportFile="report.txt", 0 existing types: 
pyNeuroML >>>  jNeuroML >>  	at org.lemsml.jlems.core.type.Lems.getComponentTypeByName(Lems.java:274)
pyNeuroML >>>  jNeuroML >>  	at org.lemsml.jlems.core.type.Component.resolve(Component.java:339)
pyNeuroML >>>  jNeuroML >>  	at org.lemsml.jlems.core.type.Component.resolve(Component.java:251)
pyNeuroML >>>  jNeuroML >>  	at org.lemsml.jlems.core.type.Component.resolve(Component.java:238)
pyNeuroML >>>  jNeuroML >>  	at org.lemsml.jlems.core.type.Component.checkResolve(Component.java:215)
pyNeuroML >>>  jNeuroML >>  	at org.lemsml.jlems.core.type.Lems.resolve(Lems.java:163)
pyNeuroML >>>  jNeuroML >>  	at org.lemsml.jlems.core.sim.LemsProcess.readModel(LemsProcess.java:82)
pyNeuroML >>>  jNeuroML >>  	at org.neuroml.export.utils.Utils.readLemsNeuroMLFile(Utils.java:261)
pyNeuroML >>>  jNeuroML >>  	at org.neuroml.export.utils.Utils.readLemsNeuroMLFile(Utils.java:245)
pyNeuroML >>>  jNeuroML >>  	at org.neuroml.export.utils.Utils$1.importFile(Utils.java:505)
pyNeuroML >>>  jNeuroML >>  	at org.lemsml.jlems.viz.datadisplay.ControlPanel.initialise(ControlPanel.java:134)
pyNeuroML >>>  jNeuroML >>  	at org.neuroml.export.utils.Utils.loadLemsFile(Utils.java:516)
pyNeuroML >>>  jNeuroML >>  	at org.neuroml.export.utils.Utils.runLemsFile(Utils.java:493)
pyNeuroML >>>  jNeuroML >>  	at org.neuroml.JNeuroML.main(JNeuroML.java:595)
pyNeuroML >>>  jNeuroML >>  INFO Jun 04,2021 01:33  (INFO) Loading LEMS file from: /home/jonrkarr/Documents/Biosimulators_pyNeuroML/tests/fixtures/LEMS_NML2_Ex5_DetCell-with-error.xml
pyNeuroML >>>  jNeuroML >>  INFO Jun 04,2021 01:33  (INFO) Reading from: /home/jonrkarr/Documents/Biosimulators_pyNeuroML/tests/fixtures/LEMS_NML2_Ex5_DetCell-with-error.xml
pyNeuroML >>>  jNeuroML >>  INFO Jun 04,2021 01:33  (INFO) Failed to read org.lemsml.jlems.core.xml.XMLException: Non matching close tag at <Lems><Targetcomponent="sim1"reportFile="report.txt"/><Includefile="Cells.xml"/><Includefile="Networks.xml"/><Includefile="Simulation.xml"/><Includefile="NaConductance.channel.nml"/><Includefile="KConductance.channel.nml"/><Includefile="LeakConductance.channel.nml"/><Includefile="NML2_SingleCompHHCell.nml"/><Simulationid="sim1"length="300ms"step="0.01ms"target="net1"><Displayid="d1"title="Ex5:HHcellwithsimplemorphology:voltage"timeScale="1ms"xmin="0"xmax="300"ymin="-90"ymax="50"><Lineid="v"quantity="hhpop[0]/v"scale="1mV"color="#ffffff"timeScale="1ms"/><Lineid="spiking"quantity="hhpop[0]/spiking"scale="0.1V"color="#004040"timeScale="1ms"/></Display><Displayid="d2"title="Ex5:HHcellwithsimplemorphology:ratevariables"timeScale="1ms"xmin="0"xmax="300"ymin="-0.1"ymax="1.1"><Lineid="m"quantity="hhpop[0]/bioPhys1/membraneProperties/NaConductances/NaConductance/m/q"scale="1"color="#000000"timeScale="1ms"/><Lineid="h"quantity="hhpop[0]/bioPhys1/membraneProperties/NaConductances/NaConductance/h/q"scale="1"color="#ff0000"timeScale="1ms"/><Lineid="n"quantity="hhpop[0]/bioPhys1/membraneProperties/KConductances/KConductance/n/q"scale="1"color="#0000ff"timeScale="1ms"/></Display><Displayid="d3"title="Ex5:HHcellwithsimplemorphology:currentdensities"timeScale="1ms"xmin="0"xmax="300"ymin="-0.1"ymax="1.1"><Lineid="ina"quantity="hhpop[0]/bioPhys1/membraneProperties/NaConductances/iDensity"scale="1"color="#000000"timeScale="1ms"/><Lineid="ik"quantity="hhpop[0]/bioPhys1/membraneProperties/KConductances/iDensity"scale="1"color="#ff0000"timeScale="1ms"/></Display><Displayid="d4"title="Ex5:HHcellwithsimplemorphology:conductancedensities"timeScale="1ms"xmin="0"xmax="300"ymin="-50"ymax="350"><Lineid="gna"quantity="hhpop[0]/bioPhys1/membraneProperties/NaConductances/gDensity"scale="1"color="#000000"timeScale="1ms"/><Lineid="gk"quantity="hhpop[0]/bioPhys1/membraneProperties/KConductances/gDensity"scale="1"color="#ff0000"timeScale="1ms"/></Display><OutputFileid="of0"fileName="results/ex5_v.dat"><OutputColumnid="v"quantity="hhpop[0]/v"/></OutputFile><OutputFileid="of1"fileName="results/ex5_vars.dat"><OutputColumnid="m"quantity="hhpop[0]/bioPhys1/membraneProperties/NaConductances/NaConductance/m/q"/><OutputColumnid="h"quantity="hhpop[0]/bioPhys1/membraneProperties/NaConductances/NaConductance/h/q"/><OutputColumnid="n"quantity="hhpop[0]/bioPhys1/membraneProperties/KConductances/KConductance/n/q"/></OutputFile></Simulation></Lems>    
pyNeuroML >>>  jNeuroML >>  tag is Displayid="d1"title="Ex5:HHcellwithsimplemorphology:voltage"timeScale="1ms"xmin="0"xmax="300"ymin="-90"ymax="50" closer is Display><Displayid="d2"title="Ex5:HHcellwithsimplemorphology:ratevariables"timeScale="1ms"xmin="0"xmax="300"ymin=
pyNeuroML >>>  jNeuroML >>  
pyNeuroML >>> Error: execute_command_in_dir returned with output: None
An exception has occurred, use %tb to see the full traceback.

SystemExit: -1

/home/jonrkarr/.local/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3445: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
```

**System information:**
 - OS: Ubuntu
 - Python version: 3.9.5
 - Version of tools in use: 0.5.11

**Additional context**

**Comment by sanjayankur31** [comment] 2021-06-15 08:59
Hi @jonrkarr , could you please upload your unformatted file? I copied the bit from your error string, but even xmllint says that it's not valid xml, so I'll have to look into the file manually to see what's going on there.

```
cat LEMS_NML2_Ex5_DetCell_unformatted.xml
<Lems><Targetcomponent="sim1"reportFile="report.txt"/><Includefile="Cells.xml"/><Includefile="Networks.xml"/><Includefile="Simulation.xml"/><Includefile="NaConductance.channel.nml"/><Includefile="KConductance.channel.nml"/><Includefile="LeakConductance.channel.nml"/><Includefile="NML2_SingleCompHHCell.nml"/><Simulationid="sim1"length="300ms"step="0.01ms"target="net1"><Displayid="d1"title="Ex5:HHcellwithsimplemorphology:voltage"timeScale="1ms"xmin="0"xmax="300"ymin="-90"ymax="50"><Lineid="v"quantity="hhpop[0]/v"scale="1mV"color="#ffffff"timeScale="1ms"/><Lineid="spiking"quantity="hhpop[0]/spiking"scale="0.1V"color="#004040"timeScale="1ms"/></Display><Displayid="d2"title="Ex5:HHcellwithsimplemorphology:ratevariables"timeScale="1ms"xmin="0"xmax="300"ymin="-0.1"ymax="1.1"><Lineid="m"quantity="hhpop[0]/bioPhys1/membraneProperties/NaConductances/NaConductance/m/q"scale="1"color="#000000"timeScale="1ms"/><Lineid="h"quantity="hhpop[0]/bioPhys1/membraneProperties/NaConductances/NaConductance/h/q"scale="1"color="#ff0000"timeScale="1ms"/><Lineid="n"quantity="hhpop[0]/bioPhys1/membraneProperties/KConductances/KConductance/n/q"scale="1"color="#0000ff"timeScale="1ms"/></Display><Displayid="d3"title="Ex5:HHcellwithsimplemorphology:currentdensities"timeScale="1ms"xmin="0"xmax="300"ymin="-0.1"ymax="1.1"><Lineid="ina"quantity="hhpop[0]/bioPhys1/membraneProperties/NaConductances/iDensity"scale="1"color="#000000"timeScale="1ms"/><Lineid="ik"quantity="hhpop[0]/bioPhys1/membraneProperties/KConductances/iDensity"scale="1"color="#ff0000"timeScale="1ms"/></Display><Displayid="d4"title="Ex5:HHcellwithsimplemorphology:conductancedensities"timeScale="1ms"xmin="0"xmax="300"ymin="-50"ymax="350"><Lineid="gna"quantity="hhpop[0]/bioPhys1/membraneProperties/NaConductances/gDensity"scale="1"color="#000000"timeScale="1ms"/><Lineid="gk"quantity="hhpop[0]/bioPhys1/membraneProperties/KConductances/gDensity"scale="1"color="#ff0000"timeScale="1ms"/></Display><OutputFileid="of0"fileName="results/ex5_v.dat"><OutputColumnid="v"quantity="hhpop[0]/v"/></OutputFile><OutputFileid="of1"fileName="results/ex5_vars.dat"><OutputColumnid="m"quantity="hhpop[0]/bioPhys1/membraneProperties/NaConductances/NaConductance/m/q"/><OutputColumnid="h"quantity="hhpop[0]/bioPhys1/membraneProperties/NaConductances/NaConductance/h/q"/><OutputColumnid="n"quantity="hhpop[0]/bioPhys1/membraneProperties/KConductances/KConductance/n/q"/></OutputFile></Simulation></Lems>

(ins)[asinha@ankur  examples(feat/issue95 $=)]$ xmllint LEMS_NML2_Ex5_DetCell_unformatted.xml
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : error parsing attribute name
<Lems><Targetcomponent="sim1"reportFile="report.txt"/><Includefile="Cells.xml"/>
                      ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : attributes construct error
<Lems><Targetcomponent="sim1"reportFile="report.txt"/><Includefile="Cells.xml"/>
                      ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : Couldn't find end of Start Tag Targetcomponent line 1
<Lems><Targetcomponent="sim1"reportFile="report.txt"/><Includefile="Cells.xml"/>
                      ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : error parsing attribute name
<Lems><Targetcomponent="sim1"reportFile="report.txt"/><Includefile="Cells.xml"/>
                                                                  ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : attributes construct error
<Lems><Targetcomponent="sim1"reportFile="report.txt"/><Includefile="Cells.xml"/>
                                                                  ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : Couldn't find end of Start Tag Includefile line 1
<Lems><Targetcomponent="sim1"reportFile="report.txt"/><Includefile="Cells.xml"/>
                                                                  ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : error parsing attribute name
tcomponent="sim1"reportFile="report.txt"/><Includefile="Cells.xml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : attributes construct error
tcomponent="sim1"reportFile="report.txt"/><Includefile="Cells.xml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : Couldn't find end of Start Tag Includefile line 1
tcomponent="sim1"reportFile="report.txt"/><Includefile="Cells.xml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : error parsing attribute name
report.txt"/><Includefile="Cells.xml"/><Includefile="Networks.xml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : attributes construct error
report.txt"/><Includefile="Cells.xml"/><Includefile="Networks.xml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : Couldn't find end of Start Tag Includefile line 1
report.txt"/><Includefile="Cells.xml"/><Includefile="Networks.xml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : error parsing attribute name
s.xml"/><Includefile="Networks.xml"/><Includefile="Simulation.xml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : attributes construct error
s.xml"/><Includefile="Networks.xml"/><Includefile="Simulation.xml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : Couldn't find end of Start Tag Includefile line 1
s.xml"/><Includefile="Networks.xml"/><Includefile="Simulation.xml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : error parsing attribute name
udefile="Simulation.xml"/><Includefile="NaConductance.channel.nml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : attributes construct error
udefile="Simulation.xml"/><Includefile="NaConductance.channel.nml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : Couldn't find end of Start Tag Includefile line 1
udefile="Simulation.xml"/><Includefile="NaConductance.channel.nml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : error parsing attribute name
aConductance.channel.nml"/><Includefile="KConductance.channel.nml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : attributes construct error
aConductance.channel.nml"/><Includefile="KConductance.channel.nml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : Couldn't find end of Start Tag Includefile line 1
aConductance.channel.nml"/><Includefile="KConductance.channel.nml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : error parsing attribute name
nductance.channel.nml"/><Includefile="LeakConductance.channel.nml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : attributes construct error
nductance.channel.nml"/><Includefile="LeakConductance.channel.nml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : Couldn't find end of Start Tag Includefile line 1
nductance.channel.nml"/><Includefile="LeakConductance.channel.nml"/><Includefile
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : error parsing attribute name
onductance.channel.nml"/><Includefile="NML2_SingleCompHHCell.nml"/><Simulationid
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : attributes construct error
onductance.channel.nml"/><Includefile="NML2_SingleCompHHCell.nml"/><Simulationid
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : Couldn't find end of Start Tag Simulationid line 1
onductance.channel.nml"/><Includefile="NML2_SingleCompHHCell.nml"/><Simulationid
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : error parsing attribute name
ll.nml"/><Simulationid="sim1"length="300ms"step="0.01ms"target="net1"><Displayid
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : attributes construct error
ll.nml"/><Simulationid="sim1"length="300ms"step="0.01ms"target="net1"><Displayid
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : Couldn't find end of Start Tag Displayid line 1
ll.nml"/><Simulationid="sim1"length="300ms"step="0.01ms"target="net1"><Displayid
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : error parsing attribute name
emorphology:voltage"timeScale="1ms"xmin="0"xmax="300"ymin="-90"ymax="50"><Lineid
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : attributes construct error
emorphology:voltage"timeScale="1ms"xmin="0"xmax="300"ymin="-90"ymax="50"><Lineid
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : Couldn't find end of Start Tag Lineid line 1
emorphology:voltage"timeScale="1ms"xmin="0"xmax="300"ymin="-90"ymax="50"><Lineid
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : error parsing attribute name
ineid="v"quantity="hhpop[0]/v"scale="1mV"color="#ffffff"timeScale="1ms"/><Lineid
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : attributes construct error
ineid="v"quantity="hhpop[0]/v"scale="1mV"color="#ffffff"timeScale="1ms"/><Lineid
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : Couldn't find end of Start Tag Lineid line 1
ineid="v"quantity="hhpop[0]/v"scale="1mV"color="#ffffff"timeScale="1ms"/><Lineid
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : Opening and ending tag mismatch: Lems line 1 and Display
uantity="hhpop[0]/spiking"scale="0.1V"color="#004040"timeScale="1ms"/></Display>
                                                                               ^
LEMS_NML2_Ex5_DetCell_unformatted.xml:1: parser error : Extra content at the end of the document
uantity="hhpop[0]/spiking"scale="0.1V"color="#004040"timeScale="1ms"/></Display>
                                                                               ^

```

**Comment by sanjayankur31** [comment] 2021-06-15 09:18
Ah, I got it. Your script does not just remove newlines, it also removes all spaces in the file. So there's no longer a space between the tag and the attribute: `<Includefile="...">`. It must be `<Include file="..."`. Since `Includefile` is not a valid tag.

So tweaking your python script to only remove spaces between attributes but to not mangle the tag names produces an unformatted xml file that runs fine:

``` python
from pyneuroml.pynml import run_lems_with_jneuroml
import re

filename = 'LEMS_NML2_Ex5_DetCell.xml'
with open(filename, 'r') as file:
    contents=file.read()

# create a non-pretty-printed copy of the example LEMS file
filename_with_error = 'LEMS_NML2_Ex5_DetCell-with-error.xml'

contents=re.sub(r'" +', r'"', contents.replace('\n', ''))
with open(filename_with_error, 'w') as file:
    file.write(contents)

# succeeds
run_lems_with_jneuroml(filename, nogui=True, plot=False)

# fails
run_lems_with_jneuroml(filename_with_error, nogui=True, plot=False)
```

**Comment by sanjayankur31** [comment] 2021-06-15 10:34
it also looks like attribute lists must be separated by spaces for it to be valid XML too. Indeed `xmllint` doesn't like it if there isn't a space in attribute lists, but the LEMS parser doesn't seem to mind so this may be implementation specific:

https://www.w3.org/TR/REC-xml/#dt-attr

Now with what looks like a well formed XML that xmllint doesn't dislike, I've managed to get another error which needs more looking into:

```
<Lems><!-- Example with Simple cell specifying segment details--><!-- This is a file which can be read and executed by the LEMS Interpreter.         It imports the LEMS definitions of the core NeuroML 2 Components,          imports in "pure" NeuroML 2 and contains some LEMS elements for running          a simulation --><Target component="sim1" reportFile="report.txt"/><Include file="Cells.xml"/><Include file="Networks.xml"/><Include file="Simulation.xml"/><!-- Including files with a <neuroml> root, "real" NeuroML 2 files --><Include file="NaConductance.channel.nml"/><Include file="KConductance.channel.nml"/><Include file="LeakConductance.channel.nml"/><Include file="NML2_SingleCompHHCell.nml"/><Simulation id="sim1" length="300ms" step="0.01ms" target="net1"><Display id="d1" title="Ex5: HH cell with simple morphology: voltage" timeScale="1ms" xmin="0" xmax="300" ymin="-90" ymax="50"><Line id="v" quantity="hhpop[0]/v" scale="1mV" color="#ffffff" timeScale="1ms"/><Line id="spiking" quantity="hhpop[0]/spiking" scale="0.1V"  color="#004040" timeScale="1ms"/><!--<Line id="l3" quantity="hhpop[0]/debugVal" scale="1V"  color="#999999" timeScale="1ms"/>--></Display> <OutputFile id="of0" fileName="results/ex5_vars.dat"><OutputColumn id="n" quantity="hhpop[0]/bioPhys1/membraneProperties/KConductances/KConductance/n/q"/></OutputFile></Simulation></Lems>
```

runs perfectly fine:

```
jnml LEMS_NML2_Ex5_DetCell-with-error2.xml
 jNeuroML v0.10.3
Loading: /home/asinha/dump/nmltest/LEMS_NML2_Ex5_DetCell-with-error2.xml with jLEMS...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/usr/share/java/jNeuroML-0.10.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO Jun 15,2021 11:30  (INFO) Loading LEMS file from: /home/asinha/dump/nmltest/LEMS_NML2_Ex5_DetCell-with-error2.xml
INFO Jun 15,2021 11:30  (INFO) Reading from: /home/asinha/dump/nmltest/LEMS_NML2_Ex5_DetCell-with-error2.xml
INFO Jun 15,2021 11:30  (INFO) Failed to read org.lemsml.jlems.core.xml.XMLException: Non matching close tag at
tag is Simulation closer is
INFO Jun 15,2021 11:30  (INFO) Finished 30000 steps in 1.08 seconds (sim duration: 300.0ms; dt: 0.01ms)
INFO Jun 15,2021 11:30  (INFO) Written to the file /home/asinha/dump/nmltest/./results/ex5_vars.dat 582392
INFO Jun 15,2021 11:30  (INFO) Simulation report will be saved in /home/asinha/dump/nmltest/report.txt
INFO Jun 15,2021 11:30  (INFO) Finished reading, building, running and displaying LEMS model
```

but, if I remove the space between the closing `</Display>` and `<OutputFile>` tags, it'll error out:


```
<Lems><!-- Example with Simple cell specifying segment details--><!-- This is a file which can be read and executed by the LEMS Interpreter.         It imports the LEMS definitions of the core NeuroML 2 Components,          imports in "pure" NeuroML 2 and contains some LEMS elements for running          a simulation --><Target component="sim1" reportFile="report.txt"/><Include file="Cells.xml"/><Include file="Networks.xml"/><Include file="Simulation.xml"/><!-- Including files with a <neuroml> root, "real" NeuroML 2 files --><Include file="NaConductance.channel.nml"/><Include file="KConductance.channel.nml"/><Include file="LeakConductance.channel.nml"/><Include file="NML2_SingleCompHHCell.nml"/><Simulation id="sim1" length="300ms" step="0.01ms" target="net1"><Display id="d1" title="Ex5: HH cell with simple morphology: voltage" timeScale="1ms" xmin="0" xmax="300" ymin="-90" ymax="50"><Line id="v" quantity="hhpop[0]/v" scale="1mV" color="#ffffff" timeScale="1ms"/><Line id="spiking" quantity="hhpop[0]/spiking" scale="0.1V"  color="#004040" timeScale="1ms"/><!--<Line id="l3" quantity="hhpop[0]/debugVal" scale="1V"  color="#999999" timeScale="1ms"/>--></Display><OutputFile id="of0" fileName="results/ex5_vars.dat"><OutputColumn id="n" quantity="hhpop[0]/bioPhys1/membraneProperties/KConductances/KConductance/n/q"/></OutputFile></Simulation></Lems>
```

```
$ jnml LEMS_NML2_Ex5_DetCell-with-error2.xml
 jNeuroML v0.10.3
Loading: /home/asinha/dump/nmltest/LEMS_NML2_Ex5_DetCell-with-error2.xml with jLEMS...
org.lemsml.jlems.core.sim.ContentError: No such children list for type: (OutputColumn) in Simulation
Existing children lists: [Childrens:
    Children {displays, type=Display}
    Children {outputs, type=OutputFile}
    Children {events, type=EventOutputFile}
]
existing childs: []

        at org.lemsml.jlems.core.type.ComponentType.getChildren(ComponentType.java:615)
        at org.lemsml.jlems.core.type.Component.resolve(Component.java:491)
        at org.lemsml.jlems.core.type.Component.resolve(Component.java:251)
        at org.lemsml.jlems.core.type.Component.resolve(Component.java:238)
        at org.lemsml.jlems.core.type.Component.checkResolve(Component.java:215)
        at org.lemsml.jlems.core.type.Lems.resolve(Lems.java:163)
        at org.lemsml.jlems.core.sim.LemsProcess.readModel(LemsProcess.java:82)
        at org.neuroml.export.utils.Utils.readLemsNeuroMLFile(Utils.java:261)
        at org.neuroml.export.utils.Utils.readLemsNeuroMLFile(Utils.java:245)
        at org.neuroml.export.utils.Utils$1.importFile(Utils.java:505)
        at org.lemsml.jlems.viz.datadisplay.ControlPanel.initialise(ControlPanel.java:134)
        at org.neuroml.export.utils.Utils.loadLemsFile(Utils.java:516)
        at org.neuroml.export.utils.Utils.runLemsFile(Utils.java:493)
        at org.neuroml.JNeuroML.main(JNeuroML.java:377)
INFO Jun 15,2021 11:32  (INFO) Loading LEMS file from: /home/asinha/dump/nmltest/LEMS_NML2_Ex5_DetCell-with-error2.xml
INFO Jun 15,2021 11:32  (INFO) Reading from: /home/asinha/dump/nmltest/LEMS_NML2_Ex5_DetCell-with-error2.xml
INFO Jun 15,2021 11:32  (INFO) Failed to read org.lemsml.jlems.core.xml.XMLException: Non matching close tag at
tag is Simulation closer is OutputFile>
```

So it *may* be something in the LEMS parser.

**Comment by sanjayankur31** [comment] 2021-06-15 16:18
Thanks @jonrkarr . I've managed to track this down and am working on a fix now. I'll open a PR as soon as I've added some regression tests to the code.

**Comment by sanjayankur31** [comment] 2021-06-15 18:07
PR pending in jLEMS, closing this ticket here. Primary issue: https://github.com/LEMS/jLEMS/issues/40

**Closed by sanjayankur31** 2021-06-15 18:07 UTC
Labels: S: needs info, T: bug
